apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: a-sample-plugin-repo
  annotations:
    github.com/project-slug: josephca/a-sample-plugin-repo
spec:
  type: other
  lifecycle: unknown
  owner: backstage
